name: "fpdart_iconica_utilities"
description: "Useful utilities for projects using fpdart"
version: "0.0.1"
repository: "https://github.com/Iconica-Development/fpdart_iconica_utilities"
homepage: "https://iconica.app"
publish_to: "https://forgejo.internal.iconica.nl/api/packages/internal/pub"

environment:
  sdk: "^3.13.1"

dependencies:
  fpdart: "^1.2.0"

dev_dependencies:
  test: ">=1.15.0 <2.0.0"
  lints: "^6.0.0"
  flutter_iconica_analysis:
    hosted: "https://forgejo.internal.iconica.nl/api/packages/internal/pub/"
    version: "^10.0.0"
